kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: cosmos-latency
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: cosmos
    apiVersion: apps/v1beta1
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type: External
      external:
        metric:
          name: cosmos-latency
        target:
          type: Value
          value: '400'
