version: "3"

services:
  anakin:
    build: .
    ports:
      - "3000:3000"

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - anakin
