apiVersion: v1
kind: Service
metadata:
  name: bits-server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3003
      protocol: TCP
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 3000
  selector:
    app: bits-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bits-server-deployment
  labels:
    app: bits-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bits-server
  template:
    metadata:
      name: bits-server
      labels:
        app: bits-server
    spec:
      containers:
          - name: bits-server
            image: bits-server
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 3003
            env:
                - name: ANAKIN_URL
                  value: https://anakin.dev.bitfighters.club/
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
                - name: ENV
                  value: dev
