apiVersion: apps/v1
kind: Deployment
metadata:
  name: anakin-dev
  namespace: default
  labels:
    app: anakin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anakin-dev
  template:
    metadata:
      labels:
        app: anakin-dev
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: anakin-dev-api

      containers:
        - name: anakin-dev
          image: 578074962452.dkr.ecr.ap-south-1.amazonaws.com/anakin-dev:latest
          imagePullPolicy: Always
          # args: ["-debug"]
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: NODE_ENV
              value: "dev"
            - name: APP_PORT
              value: "3000"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 80
          # resources:
          #   requests:
          #     memory: 8000Mi
          #     cpu: 3000m
          #     nvidia.com/gpu: 1
          #   limits:
          #     nvidia.com/gpu: 1
          #     memory: 8000Mi
          #     cpu: 3000m
          volumeMounts:
            - name: anakin-dev-log
              mountPath: /var/loco/logs/
      volumes:
        - name: anakin-dev-log
          emptyDir: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: anakin-dev
#   namespace: default
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
#     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:418915376963:certificate/ca96c082-d821-4dea-8f2c-80efb883ec1d
#     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
# spec:
#   selector:
#     app: anakin-dev
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#     - name: https
#       port: 443
#       targetPort: 80
